// basic
TXT_LABEL=label,
BTN_CMD=cmd,
BTN_LABEL=label,
LIST_PATH=listPath,
LIMIT_NUM=limitNum,

// setting
HELLO_WORLD_CHANNEL_NUM=30,

// dir path
HELLO_WORLD_FANNEL_DIR_PATH=
	"${01}/${001}",
HELLO_WORLD_LIBS_DIR_PATH=
	"${HELLO_WORLD_FANNEL_DIR_PATH}/libs",
HELLO_WORLD_JS_DIR_PATH=
	"${HELLO_WORLD_FANNEL_DIR_PATH}/js",
HELLO_WORLD_SHELL_DIR_PATH=
	"${HELLO_WORLD_FANNEL_DIR_PATH}/shell",
HELLO_WORLD_LIST_DIR_PATH=
	"${HELLO_WORLD_FANNEL_DIR_PATH}/list",
HELLO_WORLD_TEMP_DIR_PATH=
	"${HELLO_WORLD_FANNEL_DIR_PATH}/temp",


// libs path
HELLO_WORLD_SAVE_ARGS_TSV_JS_PATH=
	"${HELLO_WORLD_LIBS_DIR_PATH}/saveArgsTsv.js",
HELLO_WORLD_READ_MESSAGE_JS_PATH=
	"${HELLO_WORLD_LIBS_DIR_PATH}/readMessage.js",

// js path
HELLO_WORLD_FANNEL_PATH=
	"${0}",
HELLO_WORLD_TRIGGER_JS_PATH=
	"${HELLO_WORLD_JS_DIR_PATH}/triggerHelloWorld.js",

// shell path
HELLO_WORLD_LAUNCH_SHELL_PATH=
	"${HELLO_WORLD_SHELL_DIR_PATH}/launch_hello_world.sh",
HELLO_WORLD_EXIT_SHELL_PATH=
	"${HELLO_WORLD_SHELL_DIR_PATH}/exit_hello_world.sh",

// other
HELLO_WORLD_TEMP_ARGS_TSV_PATH=
	"${HELLO_WORLD_TEMP_DIR_PATH}/args.tsv",
HELLO_WORLD_MESSAGE_LIST_PATH=
	"${HELLO_WORLD_LIST_DIR_PATH}/messageList.txt",