
PLAY:
	:BTN:HL=
		${BTN_CMD}=jsf '${HELLO_WORLD_TRIGGER_JS_PATH}' 
			!${BTN_LABEL}=this,

MESSAGE:
	LBL:TXT:ELSB=
		${TXT_LABEL}=THIS
		|
			${LIST_PATH}=${HELLO_WORLD_MESSAGE_LIST_PATH}
				!${LIMIT_NUM}=10,